version: '3.7'
services:

        nginx:
                container_name: nginx
                build: ./nginx
                image: kang_docker/nginx
                restart: always
                ports:
                        - "80:80"
                volumes:
                        - ./kangServer:/srv/kangServer
                        - ./log:/var/log/nginx
                depends_on:
                        - django

        django:
                container_name: django
                build: ./kangServer
                image: kang_docker/django
                restart: always
                command: uwsgi --ini uwsgi.ini 
                volumes:
                        - ./kangServer:/srv/kangServer
                        - ./log:/var/log/uwsgi

